config/routes.rb
Rails.application.routes.draw do
  resources :products

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :get_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def new
    # @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to @product
    else
      render 'edit'
    end
  end

  def destroy
    @article = Product.find(params[:id])
    @article.destroy
    redirect_to products_path
  end

  private
  def get_product
    unless (@product = Product.find(params[:id]))
      redirect_to products_path and return
    end
  end

  def product_params
    params.require(:product).permit(:title, :description, :price, :image_url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Depot</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for :product, url: products_path do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </p>

  <p>
    <%= f.label :price %>
    <%= f.text_field :price %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/products/edit.html.erb
<h2>Edit Product</h2>

<%= render 'form' %>

<%= link_to 'Back to all', products_path %>
<%= link_to 'Back to Product', product_path %>

app/views/products/index.html.erb
<%= link_to 'New Product', new_product_path %>

<h1>All Products</h1>

<table>
<% @products.each do |product| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>"> 
    <td>
      <%= image_tag(product.image_url, class: 'list_image') %>
    </td>
    <td class="list_description">
      <dl>
        <dt><%= product.title %></dt>
        <dd><%= truncate(strip_tags(product.description), length: 80) %></dd>
      </dl>
    </td>
    <td class="list_actions">
    <%= link_to 'Show', product %><br/>
    <%= link_to 'Edit', edit_product_path(product) %><br/> <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>
  </tr>
<% end %> 
</table>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back to all', products_path %>

app/views/products/show.html.erb
<h2>Product</h2>

<strong>Title</strong>
<%= @product.title %><br>

<strong>Description</strong>
<%= @product.description %><br>

<strong>image_url</strong>
<%= @product.image_url %><br>

<strong>price</strong>
<%= @product.price %><br>

<%= link_to 'Back to all', products_path %>
<%= link_to 'Edit this product', edit_product_path %>